name: gamegoblins
favicon: null
layout_spectrum: 0.2439696490764618
typography_spectrum: 0.907544979127124
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ed1c25'
    - '#040707'
    - '#7bc143'
    - '#41a8df'
    - '#4e7b2c'
  brandStrength: 0.3954677563160658
  lightness: 0.5308281201869249
  saturation: 0.8344518791418523
  rhythmicContrast: 0.9092012448236346
purpose: []
